language =
    .system = Системен език
    .english = English
    .turkish = Türkçe
    .dutch = Nederlands
    .french = Français
    .german = Deutsch
    .hindi = हिन्दी
    .russian = Русский
    .chinese-simplified = Simplified Chinese
    .spanish = Español
    .portuguese = Português (Brasil)
    .arabic = العربية
    .japanese = 日本語
    .korean = 한국어
    .czech = Čeština
    .italian = Italiano
    .finnish = Suomi
    .hungarian = Magyar
    .polish = Polski
    .chinese-traditional = 繁體中文
	.bulgarian = Български

action =
    .close = Затвори
    .options = Опции
    .plugins = Приставки

ribbon-tab =
    .draw = Чертане
    .annotate = Анотиране
    .insert = Вмъкване
    .model = Модел
    .layout = Оформление
    .manage = Управление
    .view = Изглед

options =
    .language-section = Език
    .language-label = Език на интерфейса:
    .open-save-section = Отваряне и запазване
    .default-save-format-label = Формат по подразбиране за запазване:
    .default-save-format-help = Използва се при първото запазване на нова чертожна дейност. Съществуващите чертежи запазват своя тип файл и версия.
    .theme-section = Тема
    .theme-label = Тема на приложението:
    .theme-help = Смяната на базов цвят превключва на "Персонализирана". Темата генерира всеки нюанс на компонентите от тези шест цвята.
    .color-background = Фон
    .color-text = Текст
    .color-primary = Основен
    .color-success = Успех
    .color-warning = Предупреждение
    .color-danger = Опасност
    .browser-storage = Хранилище на браузъра
    .dark = Тъмна
    .default-application = Приложение по подразбиране
    .iced-theme = Iced тема:
    .theme = Тема

command-line =
    .ready = Open CAD Studio е готов.
    .hint = Въведи команда или използвай лентата. Отвори OBJ от раздел "Вмъкване".
    .label = Команда:
    .literal-spaces = Буквални интервали: Интервалът остава в реда, вместо да изпълнява командата. Остава включено, докато не се изключи.
    .invalid = Невалидно
    .unable-to-save-file-is-in-use = Не може да се запази: файлът се използва.

start =
    .new-drawing = Нов чертеж
    .open-file = Отвори файл…
    .donate = Дари
    .send-feedback = Изпрати обратна връзка
    .sponsors = Спонсори
    .tutorials = Уроци
    .loading-videos = Зареждане на видеа…
    .videos-online = Видеата се зареждат от интернет.
    .open-playlist = Отвори плейлиста в YouTube
    .discussions = Дискусии
    .pinned = Закачени
    .loading-discussions = Зареждане на дискусии…
    .discussions-online = Дискусиите се зареждат от GitHub.
    .open-discussions = Отвори дискусиите в GitHub
    .supporters = Поддръжници
    .support-on-patreon = Подкрепи в Patreon
    .recent-files = Скорошни файлове
    .videos = Видеа
    .welcome = Добре дошъл
    .recent-documents = Скорошни документи
    .no-recent-files = Файловете, които отвориш, ще се появят тук.
    .browser-storage = Хранилище на браузъра
    .keep-recent-files = Пази скорошните файлове

modal =
    .about = Относно
    .keyboard-shortcuts = Клавишни комбинации
    .command-aliases = Псевдоними на команди
    .find-replace = Намери и замени
    .plugin-manager = Мениджър на приставки
    .update-available = Налична е актуализация
    .layer-manager = Мениджър на слоеве
    .layer-state-manager = Мениджър на състояния на слоеве
    .edit-layer-state = Редактирай състояние на слой
    .plot = Плотиране
    .layout-manager = Мениджър на оформления
    .scale-manager = Мениджър на мащаби
    .annotation-object-scale = Мащаб на анотационен обект
    .plot-style-editor = Редактор на стилове за плотиране
    .text-style-manager = Мениджър на текстови стилове
    .multiline-style-manager = Мениджър на стилове за многоредов текст
    .table-style-manager = Мениджър на стилове на таблици
    .multileader-style-manager = Мениджър на стилове на многоводачи
    .dimension-style-manager = Мениджър на стилове за оразмеряване
    .default-application = Приложение по подразбиране
    .save-warning = Предупреждение при запазване
    .unable-save = Чертежът не може да бъде запазен
    .drawing-changed = Чертежът е променен на диска
    .delete-layer = Изтрий слой
    .unsaved-changes = Незапазени промени
    .unsaved-save-prompt = Искаш ли да запазиш промените?
    .point-style = Стил на точка
    .attribute-editor = Редактор на атрибути
    .save-drawing-as = Запази чертежа като
    .recovery-report = Отчет за възстановяване на чертеж
    .recovery-prompt = Възстановяване на чертеж
    .file-name-could-not-be-saved = "__ocs_arg_file_name__" не можа да бъде запазен.
    .file-name-was-changed-by-another-application = "__ocs_arg_file_name__" беше променен от друго приложение.
    .count-selected-layers = __ocs_arg_count__ избрани слоя
    .subject-still-has-count-obj-deleting-will-also =
        __ocs_arg_subject__ все още __ocs_arg_has__ __ocs_arg_count__ __ocs_arg_obj__.
        Изтриването ще премахне и __ocs_arg_those__ от чертежа. Продължи ли?
    .delete-objects = Изтрий обекти
    .details-error = Подробности: __ocs_arg_error__
    .file-name = Име на файл:
    .format = Формат:
    .layer-name = Слой "__ocs_arg_name__"
    .make-open-cad-studio-your-default-cad-app = Да направим ли Open CAD Studio твое CAD приложение по подразбиране?
    .not-now = Не сега
    .open-dwg-and-dxf-drawings-in-open-cad-studio-b = Отваряй .dwg и .dxf чертежи в Open CAD Studio по подразбиране. Можеш да промениш това по-късно в системните настройки.
    .path-path = Път: __ocs_arg_path__
    .reload-from-disk = Презареди от диска
    .save-as = Запази като...
    .saving-now-could-destroy-those-external-change = Запазването сега може да унищожи тези външни промени. Презареди копието от диска, запази локалната си работа другаде, или изрично го презапиши.
    .the-file-is-open-or-being-used-by-another-appl = Файлът е отворен или се използва от друго приложение. Затвори го там и опитай отново, или запази този чертеж под друго име.
    .the-selected-layer-state-is-no-longer-availabl = Избраното състояние на слой вече не е налично.
    .this-drawing-contains-count-aec-civil-objects =
        Този чертеж съдържа __ocs_arg_count__ AEC/Civil обекта, които "__ocs_arg_target__" не може да запази, затова няма да бъдат запазени.
        За да ги запазиш, запази в изходната версия (__ocs_arg_src_version__).
    .yes-set-as-default = Да, задай по подразбиране
    .has = има
    .hold = задържа
    .objects = обекта
    .that-object = този обект
    .those-objects = тези обекти

clipboard =
    .no-supported-content = Клипбордът не съдържа поддържан текст или чертожни обекти.
    .unavailable = Системният клипборд не е наличен.
    .occupied = Системният клипборд в момента се използва. Опитай отново.
    .conversion-failed = Текстът от клипборда не можа да бъде прочетен.
    .copybase-specify-base-point = COPYBASE  Посочи базова точка:
    .copy-to-clipboard = Копирай в клипборда
    .cut = Изрежи
    .cut-to-clipboard = Изрежи в клипборда
    .pasteclip-pick-insertion-point = PASTECLIP  Избери точка на вмъкване:
    .paste-as-block = Постави като блок
    .paste-from-clipboard = Постави от клипборда
    .paste-to-original-coordinates = Постави в оригиналните координати

viewport =
    .split-vertical = Раздели изгледа вертикално
    .split-horizontal = Раздели изгледа хоризонтално
    .move = Премести изгледа
    .close = Затвори изгледа

recovery =
    .opened-with-repairs = Чертежът е отворен с отчет за възстановяване
    .open-failed = Чертежът не можа да бъде отворен
    .repaired-description = При отварянето на чертежа бяха открити проблеми. Прегледай отчета; ако чертожните данни са възстановени, запази ги като нов файл.
    .failed-description = Възстановяването не успя да генерира използваеми чертожни данни. Прегледай отчета и опитай резервно копие или копие от автоматично запазване.
    .entities-checked = Проверени обекти
    .issues-found = Открити проблеми
    .entities-removed = Премахнати обекти
    .references-checked = Проверени препратки
    .referenced-entities-removed = Премахнати препратени обекти
    .references-unavailable = Препратките не са налични
    .log-path = Дневник за възстановяване
    .log-write-failed = Дневникът за възстановяване не можа да бъде записан
    .log-download-ready = Отчетът за възстановяване е готов за изтегляне.
    .save-copy = Запази възстановено копие
    .show-log = Покажи дневника за възстановяване
    .save-new-file-required = Възстановен чертеж трябва да бъде запазен в нов файл.
    .prompt-heading = Обикновеното отваряне се провали
    .prompt-description = Чертежът не беше променен. Режимът на възстановяване може да опита да спаси използваеми данни, но повредените записи може да бъдат пропуснати. Искаш ли да продължиш?
    .attempt = Опитай възстановяване
    .decline = Отказ

area =
    .option-objects = Обекти
    .option-back = Назад
    .option-add = Добави площ
    .option-subtract = Извади площ
    .prompt-first = AREA  Посочи първата ъглова точка или [Обекти/Добави площ/Извади площ] <Обекти>:
    .prompt-add = AREA ADD  Посочи първата ъглова точка или [Обекти/Извади площ] <Обекти>:
    .prompt-subtract = AREA SUBTRACT  Посочи първата ъглова точка или [Обекти/Добави площ] <Обекти>:
    .prompt-next = AREA  Посочи следваща точка ({ $count } избрани, Enter за изчисляване):
    .prompt-objects = AREA  Избери обекти ({ $count } избрани, Enter за изчисляване):
    .objects-not-measurable = AREA: нито един от избраните обекти няма измерима площ.
    .result = Площ = { $area },  Периметър = { $perimeter }
    .result-area-only = Площ = { $area }
    .running-result =
        Площ = { $area },  Периметър = { $perimeter }
        Обща площ = { $total_area },  Общ периметър = { $total_perimeter }
    .running-result-area-only =
        Площ = { $area }
        Обща площ = { $total_area }

command-move =
    .base =
        MOVE  Посочи базова точка  [{ $count ->
            [one] { $count } обект
           *[other] { $count } обекта
        }]:
    .target = MOVE  Посочи местоназначение  [база { $x },{ $y }]:

command-copy =
    .array-count = COPY  Въведи брой елементи за масив:
    .base =
        COPY  Посочи базова точка  [{ $count ->
            [one] { $count } обект
           *[other] { $count } обекта
        }]:
    .array-target = COPY  Посочи втора точка за масив от { $count } елемента  [база { $x },{ $y }]:
    .target =
        COPY  Посочи местоназначение  [{ $count ->
            [one] { $count } копие досега
           *[other] { $count } копия досега
        } | Масив | Enter=готово | база { $x },{ $y }]:
common =
    .none-use-shortcuts-set-key-command =   (няма — използвай: SHORTCUTS SET <клавиш> <команда>)
    .alignment-indented-label-title-case =   Подравняване:
    .background-fill-enabled =   Запълване на фона активирано
    .borders-type-weight-color-spacing-hidden =   Рамки  (тип / дебелина / цвят / разстояние / скрити)
    .data-type =   Тип на данните:
    .fill-color-indented-label-sentence-case =   Цвят на запълване:
    .format-string =   Формат:
    .off-color-ltype =   Изкл.   Цвят        Тип на линия
    .text-color-indented-label-sentence-case =   Цвят на текста:
    .text-height-indented-label-sentence-case =   Височина на текста:
    .unit-type =   Тип на единицата:
    .name-already-in-use = Името "__ocs_fmt_0__" вече се използва
    .rrggbb-or-blank = #RRGGBB или празно
    .default-parenthesized-lowercase = (по подразбиране)
    .none-parenthesized-lowercase = (няма)
    .value-1st-arrowhead-dimblk1 = 1ва стрелка (DIMBLK1)
    .value-2d-wireframe = 2D Мрежа
    .value-2nd-arrowhead-dimblk2 = 2ра стрелка (DIMBLK2)
    .value-3d-wireframe = 3D Мрежа
    .value-3dalign-aligned-the-solid-to-the-destination-p = 3DALIGN: тялото беше подравнено с целевите точки.
    .value-3dalign-each-point-triple-must-be-non-coincide = 3DALIGN: всяка тройка точки трябва да е несъвпадаща и неколинеарна.
    .value-3dalign-select-exactly-one-solid-created-this = 3DALIGN: избери точно едно тяло, създадено в тази сесия.
    .value-3dmirror-added-a-mirror-across-the-plane = 3DMIRROR: добавено огледално отражение спрямо равнина __ocs_fmt_0__.
    .value-3dmirror-could-not-determine-the-solid-s-exten = 3DMIRROR: обхватът на тялото не можа да бъде определен.
    .value-3dmirror-select-exactly-one-solid-created-this = 3DMIRROR: избери точно едно тяло, създадено в тази сесия.
    .value-3drotate-could-not-determine-the-solid-s-exten = 3DROTATE: обхватът на тялото не можа да бъде определен.
    .value-3drotate-rotated-angle-deg-about-the-axis = 3DROTATE: завъртяно на __ocs_fmt_0__° около ос __ocs_fmt_1__.
    .value-3drotate-select-exactly-one-solid-created-this = 3DROTATE: избери точно едно тяло, създадено в тази сесия.
    .align-applied = ALIGN: приложено.
    .above = Над
    .accept = Приеми
    .add = Добави
    .add-leader = Добави водач
    .align-space = Разстояние за подравняване:
    .aligned = Подравнено
    .alignment-title-case = Подравняване
    .all = Всички
    .alternate = Алтернативно
    .alternate-units = Алтернативни единици
    .angle = Ъгъл
    .angular-decimals-dimadec = Ъглови десетични (DIMADEC)
    .angular-unit-dimaunit = Ъглова единица (DIMAUNIT)
    .angular-zero-supp-dimazin = Потискане на ъглова нула (DIMAZIN)
    .annotation = Анотация
    .annotative = Анотативен
    .apparent-intersection = Видимо пресичане
    .apply = Приложи
    .apply-cell = Приложи клетка
    .apply-margins = Приложи полета
    .arc = Дъга
    .arch = Арка
    .architectural = Архитектурен
    .area = Площ
    .arrow-size = Размер на стрелка
    .arrowhead = Връх на стрелка
    .arrowhead-size = Размер на върха на стрелка
    .as-displayed = Както е показано
    .attachment-direction = Посока на закачване:
    .attribute = Атрибут
    .attributes = Атрибути
    .auto = Авто
    .bedit-block-tab-name-is-not-open = BEDIT: раздел на блок "__ocs_fmt_0__" не е отворен.
    .break-entity-type-not-supported = BREAK: типът обект не се поддържа.
    .break-fragment-s = BREAK: __ocs_fmt_0__ фрагмент(а).
    .back = Назад
    .background-color = Цвят на фона
    .backward = Назад
    .baseline = Базова линия
    .below = Под
    .block = Блок
    .block-name-created = Блок "__ocs_fmt_0__" създаден.
    .block-orig-new-name = Блок "__ocs_fmt_0__" → "__ocs_fmt_1__"
    .block-content = Съдържание на блок
    .block-color = Цвят на блок
    .block-connection = Връзка на блок
    .block-rotation = Завъртане на блок
    .blocks = Блокове
    .blue = Синьо
    .boolean-failed-the-solids-may-not-overlap = Булева операция неуспешна — телата може да не се припокриват.
    .boolean-select-exactly-two-solids-created-this = Булева операция: избери точно две тела, създадени в тази сесия.
    .bottom = Долу
    .bottom-center-title-case = Долу в средата
    .bottom-left-title-case = Долу вляво
    .bottom-right-title-case = Долу вдясно
    .bottom-attachment = Долно закачване:
    .bottom-center-sentence-case = Долу в средата
    .bottom-left-sentence-case = Долу вляво
    .bottom-right-sentence-case = Долу вдясно
    .bottomcenter = Долу в средата
    .bottomleft = Долу вляво
    .bottomright = Долу вдясно
    .box = Кутия
    .break = Прекъсни
    .brightness = Яркост
    .by-layer = По слой
    .byblock = По блок
    .bylayer = По слой
    .convtosurface-converted-n-solid-s-to-surface-s = CONVTOSURFACE: конвертирани __ocs_fmt_0__ тяло/а в повърхност/и.
    .convtosurface-select-a-solid-created-this-sess = CONVTOSURFACE: избери тяло, създадено в тази сесия.
    .coords-mode-label = COORDS = __ocs_fmt_0__ (__ocs_fmt_1__)
    .copy-specify-destination-count-copies-so-far-a = COPY  Посочи местоназначение  [__ocs_arg_count__ копия досега | Масив | Enter=готово | база __ocs_arg_bx__,__ocs_arg_by__]:
    .cancel = Отказ
    .cancel-active-command = Отказ на активна команда
    .cannot-delete-a-style-that-is-current-or-in-us = Не може да се изтрие стил, който е текущ или в употреба.
    .cannot-delete-the-model-layout = Не може да се изтрие оформлението "Модел".
    .cannot-delete-the-standard-style = Не може да се изтрие стандартният стил.
    .cannot-rename-the-model-layout = Не може да се преименува оформлението "Модел".
    .cannot-rename-the-standard-style = Не може да се преименува стандартният стил.
    .catchment-tagged-successfully = Водосборът е маркиран успешно.
    .center = Център
    .center-mark-dimcen = Централна маркировка (DIMCEN)
    .centered = Центрирано
    .centimeters = Сантиметри
    .chamfer = Скосяване
    .changelog = Дневник на промените
    .changing-a-base-colour-switches-to-custom-iced = Смяната на базов цвят превключва на "Персонализирана". Iced генерира всеки нюанс на компонентите от тези шест цвята.
    .circle = Окръжност
    .class-version = Версия на класа
    .clear = Изчисти
    .clear-all = Изчисти всичко
    .clip = Изрежи
    .clipboard = Клипборд
    .clipboard-is-empty = Клипбордът е празен.
    .close = Затвори
    .closed-filled = Затворено запълнено
    .color = Цвят
    .command-cancelled-because-the-active-drawing-s = Командата беше отказана, защото активното чертожно пространство се промени.
    .command-history-navigation = Навигация в историята на командите
    .command-label-title-case = Команда:
    .conceptual = Концептуален
    .cone = Конус
    .content = Съдържание
    .content-type = Тип на съдържанието:
    .continue = Продължи
    .contrast = Контраст
    .coordinates = Координати
    .copied-path = Копиран път: __ocs_fmt_0__
    .copy = Копирай
    .could-not-open-file-location-error = Местоположението на файла не можа да се отвори: __ocs_fmt_0__
    .could-not-rename-block-orig = Блок "__ocs_fmt_0__" не можа да бъде преименуван
    .could-not-set-default-app-err = Приложението по подразбиране не можа да се зададе: __ocs_fmt_0__
    .crossing = Пресичащ
    .current-dim-style-set-to = Текущият стил за оразмеряване е зададен на "__ocs_fmt_0__".
    .current-multiline-style = Текущ стил за многоредов текст: __ocs_fmt_0__
    .current-table-style-name = Текущ стил на таблица: __ocs_fmt_0__
    .current-text-style = Текущ текстов стил: __ocs_fmt_0__
    .custom = Персонализиран
    .cyan = Циан
    .cylinder = Цилиндър
    .dataextraction-rows-rows-fname = DATAEXTRACTION  __ocs_fmt_0__ реда → "__ocs_fmt_1__"
    .dataextraction-write-failed-e = DATAEXTRACTION: записът се провали: __ocs_fmt_0__
    .ddedit-entity-type-not-supported = DDEDIT: типът обект не се поддържа.
    .ddedit-text-updated = DDEDIT: текстът е обновен.
    .dimbreak-not-yet-implemented-nothing-changed = DIMBREAK: все още не е реализирано — нищо не е променено.
    .dimjogline-not-yet-implemented-nothing-changed = DIMJOGLINE: все още не е реализирано — нищо не е променено.
    .dimspace-spacing-adjusted = DIMSPACE  Разстоянието е коригирано.
    .divide-entity-type-not-supported-or-n-2 = DIVIDE: типът обект не се поддържа или N < 2.
    .divide-count-point-s-placed = DIVIDE: поставени __ocs_fmt_0__ точка/и.
    .draworder-select-entities-first = DRAWORDER: първо избери обекти.
    .danger = Опасност
    .data = Данни
    .data-row = Ред с данни:
    .decimal = Десетично
    .decimal-sep-ascii-dimdsep = ASCII десетичен разделител (DIMDSEP)
    .decimal-separator = Десетичен разделител
    .decimals-dimaltd = Десетични знаци (DIMALTD)
    .decimals-dimdec = Десетични знаци (DIMDEC)
    .default-title-case = По подразбиране
    .default-text = Текст по подразбиране:
    .deg-min-sec = Градус/минута/секунда
    .delete = Изтрий
    .delete-selected-entities = Изтрий избраните обекти
    .description-title-case = Описание
    .description-label-title-case = Описание:
    .diameter = Диаметър
    .dim-style = Стил за оразмеряване
    .dimension = Оразмеряване
    .dimensions = Оразмерявания
    .discard = Отхвърли
    .discussions = Дискусии
    .discussions-load-from-github = Дискусиите се зареждат от GitHub.
    .display = Показване
    .distance = Разстояние
    .donate = Дари
    .done = Готово
    .double = Двойно
    .draft = Чернова
    .draw = Чертай
    .drawing = Чертеж
    .drawing-units = Чертожни единици
    .drop-0-ft-keep-0-in = Пропусни 0 фута, задръж 0 инча
    .dynamic = Динамично
    .extrude-could-not-build-profile-select-a-close = EXTRUDE: профилът не можа да бъде изграден. Избери затворен 2D обект (окръжност, полилиния и т.н.).
    .extrude-entity-not-found = EXTRUDE: обектът не е намерен.
    .extrude-solid-created = EXTRUDE: тялото е създадено.
    .edge = Ръб
    .editing-selected = Редактиране: __ocs_arg_selected__
    .elements = Елементи:
    .ellipse = Елипса
    .enable-alternate-units-dimalt = Активирай алтернативни единици (DIMALT)
    .end-angle = Краен ъгъл
    .endpoint = Крайна точка
    .engineering = Инженерен
    .enter = Enter
    .expected-coordinates-x-y-or-a-number-got-text = Очаквани координати (x,y) или число, получено: "__ocs_fmt_0__"
    .extension = Разширение
    .extension-dimdle = Удължение (DIMDLE)
    .extension-dimexe = Удължение (DIMEXE)
    .extents = Обхват
    .find-replace-replaced-1-occurrence-of-search = НАМЕРИ/ЗАМЕНИ: заменено 1 съвпадение на "__ocs_fmt_0__".
    .find-replace-replaced-replaced-occurrence-s-of = НАМЕРИ/ЗАМЕНИ: заменени __ocs_fmt_0__ съвпадение(я) на "__ocs_fmt_1__".
    .flatshot-created-n-projected-edge-s-at-z-0 = FLATSHOT: създадени __ocs_fmt_0__ проектиран(и) ръб(ове) при Z=0.
    .flatshot-select-a-solid-created-this-session = FLATSHOT: избери тяло, създадено в тази сесия.
    .fade = Заглушаване
    .failed-to-create-layout-e = Оформлението не можа да бъде създадено: __ocs_fmt_0__
    .feet = Фута
    .fence = Ограда
    .file-locations-are-unavailable-in-the-web-appl = Местоположенията на файлове не са налични в уеб приложението.
    .fill-color-sentence-case = Цвят на запълване
    .fill-color-aci-dimtfillclr = ACI цвят на запълване (DIMTFILLCLR)
    .fillet = Заобляне
    .finalize-command-repeat-last = Завърши команда / Повтори последната
    .finalizing = Завършване…
    .find-and-replace = Намери и замени
    .first-seg-angle = Ъгъл на 1ви сегмент:
    .fit = Побиране
    .fit-dimatfit = Побиране (DIMATFIT)
    .fit-legacy-dimfit = Побиране (стар DIMFIT)
    .fixed-height = Фиксирана височина:
    .fixed-length-dimfxl = Фиксирана дължина (DIMFXL)
    .fixed-length-ext-lines-dimfxlon = Удължителни линии с фикс. дължина (DIMFXLON)
    .flat-shaded = Плоско засенчено
    .flat-shaded-edges = Плоско засенчено + ръбове
    .flow-direction = Посока на потока:
    .font-load-failed-script-e = Шрифтът не можа да се зареди (__ocs_fmt_0__): __ocs_fmt_1__
    .force-text-inside-dimtix = Принуди текста вътре (DIMTIX)
    .format = Формат
    .format-dimlunit = Формат (DIMLUNIT)
    .fraction-format-dimfrac = Формат на дроб (DIMFRAC)
    .fractional = Дробно
    .front = Отпред
    .full = Пълно
    .full-file-paths-are-unavailable-in-the-web-app = Пълните пътища на файлове не са налични в уеб приложението.
    .general = Общи
    .generate-tolerances-dimtol = Генерирай толеранси (DIMTOL)
    .geometry = Геометрия
    .gouraud-shaded = Gouraud засенчено
    .gouraud-shaded-edges = Gouraud засенчено + ръбове
    .green = Зелено
    .group = Група
    .group-created = Група "__ocs_fmt_0__" създадена.
    .groups = Групи
    .h-margin = Хоризонтално поле:
    .hatchedit-hatch-entity-not-found = HATCHEDIT: обект щриховка не е намерен.
    .hatchedit-hatch-updated = HATCHEDIT: щриховката е обновена.
    .hatchedit-not-a-hatch-entity = HATCHEDIT: не е обект щриховка.
    .handle = Манипулатор
    .hatch = Щриховка
    .header-row = Заглавен ред:
    .header-row-suppressed = Заглавният ред е потиснат
    .height = Височина
    .height-dimtxt = Височина (DIMTXT)
    .helix = Спирала
